CLIENT SENDS USER ID TO SERVER >
  SERVER STORES ID IN ARRAY >
    SERVER SENDS ARRAY OF ALL USERS TO CLIENT >
      CLIENT CAN DISPLAY ALL CURRENT USERS >

      SERVER STORES ID IN ARRAY >
      SERVER ALSO EMITS THAT USER TO CHAT
      
